version: '3.7'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./docker/development/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - jenkins
  jenkins:
    build:
      context: ./docker/toolbox
    image: jenkins/jenkins:lts
    ports:
      - 8081:8080
      - 50000:50000
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TSL_VERIFY: 1
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs:/certs/client:ro
    depends_on:
      - docker
  docker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TSL_CERTDIR: /cert
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs:/certs/client
      - docker-data:/var/lib/docker
volumes:
  jenkins-data:
  docker-certs:
  docker-data: